### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by robbieh** [algernon/potential-happiness#4]
How do I configure this to point to my Riemann server?

**Comment by algernon** [comment]
Something along [these lines](https://github.com/algernon/potential-happiness/blob/master/examples/local-log.js#L36): `modules.export.defaults.source` in the provided config should be set to the address of your Riemann server. If using the example `local-log.js` config, then you can set the `RIEMANN_HOST` environment variable, and it will use that over the default.

Does this answer your question?

**Comment by robbieh** [comment]
On Tue, Feb 13, 2018 at 03:32:49PM +0000, Gergely Nagy wrote:
> Something along these lines: modules.export.defaults.source in the provided
> config should be set to the address of your Riemann server. If using the
> example local-log.js config, then you can set the RIEMANN_HOST environment
> variable, and it will use that over the default.
> 
> Does this answer your question?

Oh brilliant that did it! Thanks! That might be a good tip to put in the README :)
